### ISSUE TITLE
Cleansing User Data in About Me

### ISSUE THREAD

**Issue by dranderson1117** [carlosvillapudua/colorCoded#23]
We are missing the code to cleanse the user data in step 7 of About Me

String aboutMe = Jsoup.clean(request.getParameter("about-me"), Whitelist.none());

**Comment by Timileyin5** [comment]
That code was making the build fail on Nico's end, so I took it out because I was told by Kevin Workman that I wasn't actually supposed to put the code in there.

**Comment by dranderson1117** [comment]
ok, I will close this out.
